version: '3.8'

services:
  web:
    build: .
    command:
      - sh
      - -c
      - |
        python /code/manage.py makemigrations &&
        python /code/manage.py migrate &&
        python /code/manage.py runserver 0.0.0.0:8000
        python /code/manage.py collectstatic
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: